import ApplicantNavigation from "@/components/ui/ApplicantNavigation";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { EdgeStoreProvider } from '@/lib/edgestore'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Toaster position="top-center" />
                <ApplicantNavigation />
                <EdgeStoreProvider>{children}</EdgeStoreProvider>
            </body>
        </html>
    );
}
