import ApplicantNavigation from "@/components/applicant/ApplicantNavigation";
import { validateRequest } from "@/lib/auth";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    const { user } = await validateRequest();

    return (
        <html lang="en">
            <body className={inter.className}>
                <Toaster position="top-center" />
                {user && !(<ApplicantNavigation />)}
                {children}
            </body>
        </html>
    );
}
